seed: 42
run_name: run-01

train:
  epochs: 3
  warmup_ratio: 0.06
  weight_decay: 0.01
  fp16: true
  gradient_checkpointing: true
  batch_size: auto
  grad_accum: auto
  eval_strategy: steps
  eval_steps: 200
  save_strategy: steps
  save_steps: 200
  save_total_limit: 3
  metric_for_best_model: rougeL
  greater_is_better: true
  load_best_model_at_end: true
  output_dir: outputs/run-01

data:
  format: chat
  template_path: chat_templates/default.jinja
  split:
    train_ratio: 0.7
    val_ratio: 0.1
    test_ratio: 0.2

logging:
  backend: tensorboard
  log_interval: 20
